<?xml version="1.0" ?>
<!DOCTYPE main [
  <!ELEMENT main (DATA_RECORD*)>
  <!ELEMENT DATA_RECORD (CODIGO,NOMBRE?,FECHA,LUGAR?,TIPO,CALIDADES?,INCORPORAR_A_CVN?)+>
  <!ELEMENT CODIGO (#PCDATA)>
  <!ELEMENT NOMBRE (#PCDATA)>
  <!ELEMENT FECHA (#PCDATA)>
  <!ELEMENT LUGAR (#PCDATA)>
  <!ELEMENT TIPO (#PCDATA)>
  <!ELEMENT CALIDADES (#PCDATA)>
  <!ELEMENT INCORPORAR_A_CVN (#PCDATA)>
]>
<main>
  <DATA_RECORD>
    <CODIGO>1</CODIGO>
    <NOMBRE>PRIMERA FERIA INTERNACIONAL DE TECNOLOGIAS EMERGENTES, CIENCIA Y EMPRESA &#40;CITEC&#41;</NOMBRE>
    <FECHA>2000/11/27 00:00:00</FECHA>
    <LUGAR>BARCELONA- ESPA&#209;A</LUGAR>
    <TIPO>C</TIPO>
    <CALIDADES></CALIDADES>
    <INCORPORAR_A_CVN></INCORPORAR_A_CVN>
  </DATA_RECORD>
 
</main>
