<?xml version="1.0" ?>
<!DOCTYPE main [
  <!ELEMENT main (DATA_RECORD*)>
  <!ELEMENT DATA_RECORD (RESOP_NUMERO?,RESOP_REQCODIGO?,RESOP_CUMPLEREQ)+>
  <!ELEMENT RESOP_NUMERO (#PCDATA)>
  <!ELEMENT RESOP_REQCODIGO (#PCDATA)>
  <!ELEMENT RESOP_CUMPLEREQ (#PCDATA)>
]>
<main>
  <DATA_RECORD>
    <RESOP_NUMERO>9586</RESOP_NUMERO>
    <RESOP_REQCODIGO>a</RESOP_REQCODIGO>
    <RESOP_CUMPLEREQ>S</RESOP_CUMPLEREQ>
  </DATA_RECORD>
 
</main>
