<?xml version="1.0" ?>
<!DOCTYPE main [
  <!ELEMENT main (DATA_RECORD*)>
  <!ELEMENT DATA_RECORD (IDGRUPOINVESTIGACION,NUMERO,CODTIPOCONCEPTO,TEXTO)+>
  <!ELEMENT IDGRUPOINVESTIGACION (#PCDATA)>
  <!ELEMENT NUMERO (#PCDATA)>
  <!ELEMENT CODTIPOCONCEPTO (#PCDATA)>
  <!ELEMENT TEXTO (#PCDATA)>
]>
<main>
  <DATA_RECORD>
    <IDGRUPOINVESTIGACION>E005-04</IDGRUPOINVESTIGACION>
    <NUMERO>8</NUMERO>
    <CODTIPOCONCEPTO>DESCRIPTORES</CODTIPOCONCEPTO>
    <TEXTO>EDAFOLOGIA</TEXTO>
  </DATA_RECORD>
</main>
