<?xml version="1.0" ?>
<!DOCTYPE main [
  <!ELEMENT main (DATA_RECORD*)>
  <!ELEMENT DATA_RECORD (CODIGO,TITULO?,ANO?,PAIS_CODIGO?,REIS_ISSN?,CATALOGO?,AREA?,NOMBRE_REVISTA?,CUARTIL_REVISTA?,URL_REVISTA?,VOLUMEN?,NUMERO?,PAGDESDE?,PAGHASTA?,NUMPAG?,COAUT_EXT?)+>
  <!ELEMENT CODIGO (#PCDATA)>
  <!ELEMENT TITULO (#PCDATA)>
  <!ELEMENT ANO (#PCDATA)>
  <!ELEMENT PAIS_CODIGO (#PCDATA)>
  <!ELEMENT REIS_ISSN (#PCDATA)>
  <!ELEMENT CATALOGO (#PCDATA)>
  <!ELEMENT AREA (#PCDATA)>
  <!ELEMENT NOMBRE_REVISTA (#PCDATA)>
  <!ELEMENT CUARTIL_REVISTA (#PCDATA)>
  <!ELEMENT URL_REVISTA (#PCDATA)>
  <!ELEMENT VOLUMEN (#PCDATA)>
  <!ELEMENT NUMERO (#PCDATA)>
  <!ELEMENT PAGDESDE (#PCDATA)>
  <!ELEMENT PAGHASTA (#PCDATA)>
  <!ELEMENT NUMPAG (#PCDATA)>
  <!ELEMENT COAUT_EXT (#PCDATA)>
]>
<main>
  <DATA_RECORD>
    <CODIGO>334</CODIGO>
    <TITULO>KINETIC STUDY OF THE TRANSIENT PHASE OF A CHEMICAL REACTION SYSTEM COUPLED TO AN ENZYMATICALLY CATALYZED STEP. APPLICATION TO T</TITULO>
    <ANO>1987</ANO>
    <PAIS_CODIGO></PAIS_CODIGO>
    <REIS_ISSN></REIS_ISSN>
    <CATALOGO></CATALOGO>
    <AREA></AREA>
    <NOMBRE_REVISTA></NOMBRE_REVISTA>
    <CUARTIL_REVISTA></CUARTIL_REVISTA>
    <URL_REVISTA></URL_REVISTA>
    <VOLUMEN>27</VOLUMEN>
    <NUMERO></NUMERO>
    <PAGDESDE>15</PAGDESDE>
    <PAGHASTA>25</PAGHASTA>
    <NUMPAG></NUMPAG>
    <COAUT_EXT>N</COAUT_EXT>
  </DATA_RECORD>
</main>
