<?xml version="1.0" ?>
<!DOCTYPE main [
  <!ELEMENT main (DATA_RECORD*)>
  <!ELEMENT DATA_RECORD (IDDOCUMENTO?,NUMERO?,IDTIPOGASTOAYUDA?,DESCRIPCION?,NUMEROANUALIDAD?,IMPORTE?,PERMITIDO?,OBSERVACIONES?)+>
  <!ELEMENT IDDOCUMENTO (#PCDATA)>
  <!ELEMENT NUMERO (#PCDATA)>
  <!ELEMENT IDTIPOGASTOAYUDA (#PCDATA)>
  <!ELEMENT DESCRIPCION (#PCDATA)>
  <!ELEMENT NUMEROANUALIDAD (#PCDATA)>
  <!ELEMENT IMPORTE (#PCDATA)>
  <!ELEMENT PERMITIDO (#PCDATA)>
  <!ELEMENT OBSERVACIONES (#PCDATA)>
]>
<main>
  <DATA_RECORD>
    <IDDOCUMENTO>RAYP-A-2015-12978</IDDOCUMENTO>
    <NUMERO>1</NUMERO>
    <IDTIPOGASTOAYUDA>1005</IDTIPOGASTOAYUDA>
    <DESCRIPCION>GASTOS DE AUDITORIA</DESCRIPCION>
    <NUMEROANUALIDAD></NUMEROANUALIDAD>
    <IMPORTE>4800</IMPORTE>
    <PERMITIDO>S</PERMITIDO>
    <OBSERVACIONES></OBSERVACIONES>
  </DATA_RECORD>
 
</main>
