<?xml version="1.0" ?>
<!DOCTYPE main [
  <!ELEMENT main (DATA_RECORD*)>
  <!ELEMENT DATA_RECORD (IDDOCUMENTO?,IDPERSONA?,CODIGOTIPOPARTICIPACION?)+>
  <!ELEMENT IDDOCUMENTO (#PCDATA)>
  <!ELEMENT IDPERSONA (#PCDATA)>
  <!ELEMENT CODIGOTIPOPARTICIPACION (#PCDATA)>
]>
<main>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-2008-9834</IDDOCUMENTO>
    <IDPERSONA>142780</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>INV</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-2008-9834</IDDOCUMENTO>
    <IDPERSONA>142651</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>INV</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-2008-9834</IDDOCUMENTO>
    <IDPERSONA>1081</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>INV</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-2008-9834</IDDOCUMENTO>
    <IDPERSONA>4432</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>INV</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-2008-9834</IDDOCUMENTO>
    <IDPERSONA>137793</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>INV</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-2008-9834</IDDOCUMENTO>
    <IDPERSONA>140929</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>INV</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-2008-9834</IDDOCUMENTO>
    <IDPERSONA>1931</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>INV</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-2007-9249</IDDOCUMENTO>
    <IDPERSONA>2643</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>IPRE</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-2007-9249</IDDOCUMENTO>
    <IDPERSONA>985</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>INV</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-2007-9249</IDDOCUMENTO>
    <IDPERSONA>5528</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>INV</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-2007-9249</IDDOCUMENTO>
    <IDPERSONA>5449</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>INV</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-2007-9249</IDDOCUMENTO>
    <IDPERSONA>6294</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>INV</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-2007-9249</IDDOCUMENTO>
    <IDPERSONA>5538</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>INV</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-2007-9247</IDDOCUMENTO>
    <IDPERSONA>549</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>IPRE</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-2007-9247</IDDOCUMENTO>
    <IDPERSONA>5027</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>INV</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-2007-9247</IDDOCUMENTO>
    <IDPERSONA>5098</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>INV</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-2007-9247</IDDOCUMENTO>
    <IDPERSONA>5369</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>INV</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-2007-9247</IDDOCUMENTO>
    <IDPERSONA>1961</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>INV</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-2007-9247</IDDOCUMENTO>
    <IDPERSONA>4384</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>INV</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-2008-9908</IDDOCUMENTO>
    <IDPERSONA>3532</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>IPRE</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-2008-9908</IDDOCUMENTO>
    <IDPERSONA>1376</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>INV</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-2008-9908</IDDOCUMENTO>
    <IDPERSONA>1128</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>INV</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-2008-9908</IDDOCUMENTO>
    <IDPERSONA>7348</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>INV</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-2008-9908</IDDOCUMENTO>
    <IDPERSONA>141401</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>INV</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-2008-9908</IDDOCUMENTO>
    <IDPERSONA>1257</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>INV</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-2008-9908</IDDOCUMENTO>
    <IDPERSONA>141402</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>INV</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-2008-9908</IDDOCUMENTO>
    <IDPERSONA>131623</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>INV</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-2008-9908</IDDOCUMENTO>
    <IDPERSONA>141403</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>INV</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-2008-9908</IDDOCUMENTO>
    <IDPERSONA>141404</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>INV</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-2008-9908</IDDOCUMENTO>
    <IDPERSONA>1100</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>INV</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-2008-9908</IDDOCUMENTO>
    <IDPERSONA>27210</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>INV</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-2008-9907</IDDOCUMENTO>
    <IDPERSONA>3532</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>IPRE</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-2008-9907</IDDOCUMENTO>
    <IDPERSONA>1376</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>INV</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-2008-9907</IDDOCUMENTO>
    <IDPERSONA>1128</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>INV</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-2008-9907</IDDOCUMENTO>
    <IDPERSONA>7348</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>INV</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-2008-9907</IDDOCUMENTO>
    <IDPERSONA>141401</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>INV</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-2008-9907</IDDOCUMENTO>
    <IDPERSONA>1257</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>INV</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-2008-9907</IDDOCUMENTO>
    <IDPERSONA>141402</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>INV</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-2008-9907</IDDOCUMENTO>
    <IDPERSONA>131623</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>INV</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-2008-9907</IDDOCUMENTO>
    <IDPERSONA>141403</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>INV</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-2008-9907</IDDOCUMENTO>
    <IDPERSONA>141404</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>INV</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-2008-9907</IDDOCUMENTO>
    <IDPERSONA>1100</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>INV</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-2008-9907</IDDOCUMENTO>
    <IDPERSONA>27210</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>INV</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-2008-9920</IDDOCUMENTO>
    <IDPERSONA>1714</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>IPRE</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-2000-5328</IDDOCUMENTO>
    <IDPERSONA>1576</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>IPRE</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-2000-4981</IDDOCUMENTO>
    <IDPERSONA>152505</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>INV</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-2000-4981</IDDOCUMENTO>
    <IDPERSONA>152519</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>INV</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-2000-4981</IDDOCUMENTO>
    <IDPERSONA>992</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>IPRE</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-2000-4981</IDDOCUMENTO>
    <IDPERSONA>95</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>INV</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-2000-4981</IDDOCUMENTO>
    <IDPERSONA>939</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>INV</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-2000-4981</IDDOCUMENTO>
    <IDPERSONA>2027</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>INV</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-2000-4981</IDDOCUMENTO>
    <IDPERSONA>838</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>INV</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-2000-4981</IDDOCUMENTO>
    <IDPERSONA>327</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>INV</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-2000-5091</IDDOCUMENTO>
    <IDPERSONA>1239</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>IPRE</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-2000-5091</IDDOCUMENTO>
    <IDPERSONA>2910</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>INV</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-2000-5091</IDDOCUMENTO>
    <IDPERSONA>3435</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>INV</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-2000-5091</IDDOCUMENTO>
    <IDPERSONA>2891</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>INV</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-1998-4185</IDDOCUMENTO>
    <IDPERSONA>1059</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>INV</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-1998-4185</IDDOCUMENTO>
    <IDPERSONA>152470</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>INV</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-1998-4185</IDDOCUMENTO>
    <IDPERSONA>1964</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>INV</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-1998-4185</IDDOCUMENTO>
    <IDPERSONA>2970</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>INV</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-1998-4185</IDDOCUMENTO>
    <IDPERSONA>633</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>INV</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-1998-4185</IDDOCUMENTO>
    <IDPERSONA>487</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>IPRE</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-1998-4185</IDDOCUMENTO>
    <IDPERSONA>75</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>INV</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-1998-4185</IDDOCUMENTO>
    <IDPERSONA>48</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>INV</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-1998-4185</IDDOCUMENTO>
    <IDPERSONA>67</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>INV</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-1998-4185</IDDOCUMENTO>
    <IDPERSONA>496</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>INV</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-1998-4185</IDDOCUMENTO>
    <IDPERSONA>3161</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>INV</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-1998-4185</IDDOCUMENTO>
    <IDPERSONA>3933</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>INV</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-1998-4185</IDDOCUMENTO>
    <IDPERSONA>4165</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>INV</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-1998-4185</IDDOCUMENTO>
    <IDPERSONA>2791</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>INV</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-1998-4183</IDDOCUMENTO>
    <IDPERSONA>873</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>IPRE</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-1998-4183</IDDOCUMENTO>
    <IDPERSONA>1209</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>INV</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-1998-4183</IDDOCUMENTO>
    <IDPERSONA>609</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>INV</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-1998-4183</IDDOCUMENTO>
    <IDPERSONA>1545</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>INV</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-1998-4183</IDDOCUMENTO>
    <IDPERSONA>348</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>INV</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-1998-4183</IDDOCUMENTO>
    <IDPERSONA>128607</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>INV</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-1998-4183</IDDOCUMENTO>
    <IDPERSONA>132545</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>INV</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-1998-4183</IDDOCUMENTO>
    <IDPERSONA>132546</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>INV</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-1998-4183</IDDOCUMENTO>
    <IDPERSONA>20253</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>INV</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-1998-4622</IDDOCUMENTO>
    <IDPERSONA>280</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>IPRE</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-1998-4622</IDDOCUMENTO>
    <IDPERSONA>132779</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>INV</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-1998-4622</IDDOCUMENTO>
    <IDPERSONA>38836</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>INV</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-1998-4291</IDDOCUMENTO>
    <IDPERSONA>3005</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>INV</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-1998-4291</IDDOCUMENTO>
    <IDPERSONA>3384</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>INV</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-1998-4291</IDDOCUMENTO>
    <IDPERSONA>2136</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>INV</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-1998-4291</IDDOCUMENTO>
    <IDPERSONA>1738</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>IPRE</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-1998-4197</IDDOCUMENTO>
    <IDPERSONA>3237</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>IPRE</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-1998-4197</IDDOCUMENTO>
    <IDPERSONA>323</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>INV</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-1998-4197</IDDOCUMENTO>
    <IDPERSONA>4350</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>INV</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-1998-3609</IDDOCUMENTO>
    <IDPERSONA>1746</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>IPRE</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-1998-3609</IDDOCUMENTO>
    <IDPERSONA>1500</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>INV</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-1998-3608</IDDOCUMENTO>
    <IDPERSONA>3504</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>IPRE</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-1998-3608</IDDOCUMENTO>
    <IDPERSONA>3342</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>INV</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-1998-3608</IDDOCUMENTO>
    <IDPERSONA>2960</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>INV</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-1999-5403</IDDOCUMENTO>
    <IDPERSONA>734</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>INV</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-1999-5403</IDDOCUMENTO>
    <IDPERSONA>2971</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>IPRE</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-1999-5403</IDDOCUMENTO>
    <IDPERSONA>665</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>INV</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-1999-5403</IDDOCUMENTO>
    <IDPERSONA>1734</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>INV</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-1999-5403</IDDOCUMENTO>
    <IDPERSONA>797</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>INV</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-1999-5403</IDDOCUMENTO>
    <IDPERSONA>130000</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>INV</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-1999-5403</IDDOCUMENTO>
    <IDPERSONA>1126</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>INV</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-1999-5403</IDDOCUMENTO>
    <IDPERSONA>1418</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>INV</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-1999-5402</IDDOCUMENTO>
    <IDPERSONA>4016</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>INV</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-1999-5402</IDDOCUMENTO>
    <IDPERSONA>3245</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>IPRE</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-1999-5402</IDDOCUMENTO>
    <IDPERSONA>131172</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>INV</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-1999-5402</IDDOCUMENTO>
    <IDPERSONA>129375</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>INV</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-1999-5402</IDDOCUMENTO>
    <IDPERSONA>888</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>INV</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-1999-5177</IDDOCUMENTO>
    <IDPERSONA>985</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>IPRE</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-1999-4597</IDDOCUMENTO>
    <IDPERSONA>2945</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>IPRE</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-1999-4597</IDDOCUMENTO>
    <IDPERSONA>136</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>INV</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-1999-4597</IDDOCUMENTO>
    <IDPERSONA>1119</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>INV</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-1999-4597</IDDOCUMENTO>
    <IDPERSONA>1723</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>INV</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-1999-4597</IDDOCUMENTO>
    <IDPERSONA>2916</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>INV</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-1999-4597</IDDOCUMENTO>
    <IDPERSONA>132772</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>INV</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-1999-4597</IDDOCUMENTO>
    <IDPERSONA>3639</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>INV</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-1999-4597</IDDOCUMENTO>
    <IDPERSONA>521</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>INV</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-1999-4597</IDDOCUMENTO>
    <IDPERSONA>2711</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>INV</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-2000-5354</IDDOCUMENTO>
    <IDPERSONA>569</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>IPRE</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-2000-5354</IDDOCUMENTO>
    <IDPERSONA>3111</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>INV</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-2000-5354</IDDOCUMENTO>
    <IDPERSONA>2833</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>INV</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-2000-5354</IDDOCUMENTO>
    <IDPERSONA>1404</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>INV</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-2000-5354</IDDOCUMENTO>
    <IDPERSONA>1257</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>INV</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-1998-4166</IDDOCUMENTO>
    <IDPERSONA>1410</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>IPRE</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-1998-4166</IDDOCUMENTO>
    <IDPERSONA>1072</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>INV</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-1998-4166</IDDOCUMENTO>
    <IDPERSONA>844</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>INV</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-1998-4166</IDDOCUMENTO>
    <IDPERSONA>3887</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>INV</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-1998-4166</IDDOCUMENTO>
    <IDPERSONA>4981</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>INV</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-1998-4165</IDDOCUMENTO>
    <IDPERSONA>491</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>IPRE</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-1998-4165</IDDOCUMENTO>
    <IDPERSONA>1058</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>INV</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-1998-4165</IDDOCUMENTO>
    <IDPERSONA>129474</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>INV</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-1998-4165</IDDOCUMENTO>
    <IDPERSONA>30211</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>INV</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-1998-4165</IDDOCUMENTO>
    <IDPERSONA>152526</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>INV</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-1998-4164</IDDOCUMENTO>
    <IDPERSONA>787</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>IPRE</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-1998-4164</IDDOCUMENTO>
    <IDPERSONA>792</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>INV</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-1998-4164</IDDOCUMENTO>
    <IDPERSONA>2995</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>INV</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-1998-4164</IDDOCUMENTO>
    <IDPERSONA>1411</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>INV</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-1998-4164</IDDOCUMENTO>
    <IDPERSONA>2731</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>INV</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-1998-4164</IDDOCUMENTO>
    <IDPERSONA>1907</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>INV</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-1998-4164</IDDOCUMENTO>
    <IDPERSONA>2951</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>INV</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-1998-4164</IDDOCUMENTO>
    <IDPERSONA>2834</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>INV</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-1998-4164</IDDOCUMENTO>
    <IDPERSONA>132535</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>INV</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-1998-4163</IDDOCUMENTO>
    <IDPERSONA>670</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>IPRE</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-1998-4163</IDDOCUMENTO>
    <IDPERSONA>3390</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>INV</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-1998-4163</IDDOCUMENTO>
    <IDPERSONA>2091</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>INV</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-1998-4163</IDDOCUMENTO>
    <IDPERSONA>2630</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>INV</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-1998-4163</IDDOCUMENTO>
    <IDPERSONA>717</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>INV</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-1998-4163</IDDOCUMENTO>
    <IDPERSONA>2346</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>INV</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-1998-4163</IDDOCUMENTO>
    <IDPERSONA>2054</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>INV</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-1998-4163</IDDOCUMENTO>
    <IDPERSONA>351</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>INV</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-1998-4163</IDDOCUMENTO>
    <IDPERSONA>1073</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>INV</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-1998-4163</IDDOCUMENTO>
    <IDPERSONA>72928</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>INV</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-1998-4163</IDDOCUMENTO>
    <IDPERSONA>28277</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>INV</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-1998-4163</IDDOCUMENTO>
    <IDPERSONA>132531</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>INV</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-1998-4163</IDDOCUMENTO>
    <IDPERSONA>132532</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>INV</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-1998-4163</IDDOCUMENTO>
    <IDPERSONA>132533</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>INV</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-1998-4163</IDDOCUMENTO>
    <IDPERSONA>134994</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>INV</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-1998-4163</IDDOCUMENTO>
    <IDPERSONA>51220</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>INV</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-1998-4163</IDDOCUMENTO>
    <IDPERSONA>134687</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>INV</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-1998-4163</IDDOCUMENTO>
    <IDPERSONA>132534</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>INV</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-1998-4163</IDDOCUMENTO>
    <IDPERSONA>34761</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>INV</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-2001-5686</IDDOCUMENTO>
    <IDPERSONA>257</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>IPRE</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-2001-5686</IDDOCUMENTO>
    <IDPERSONA>2049</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>INV</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-2001-5686</IDDOCUMENTO>
    <IDPERSONA>2656</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>INV</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-2001-5686</IDDOCUMENTO>
    <IDPERSONA>2825</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>INV</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-2001-5686</IDDOCUMENTO>
    <IDPERSONA>129212</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>INV</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-2001-5686</IDDOCUMENTO>
    <IDPERSONA>4063</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>INV</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-2001-5686</IDDOCUMENTO>
    <IDPERSONA>21789</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>INV</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-2001-5686</IDDOCUMENTO>
    <IDPERSONA>5304</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>INV</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-2001-5686</IDDOCUMENTO>
    <IDPERSONA>6081</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>INV</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-2001-5686</IDDOCUMENTO>
    <IDPERSONA>134992</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>INV</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-1998-4159</IDDOCUMENTO>
    <IDPERSONA>2969</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>INV</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-1998-4159</IDDOCUMENTO>
    <IDPERSONA>1224</IDPERSONA>
    <CODIGOTIPOPARTICIPACION>IPRE</CODIGOTIPOPARTICIPACION>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDOCUMENTO>SAY-A-1998-4158</IDDOCUMENTO>