<?xml version="1.0" ?>
<!DOCTYPE main [
  <!ELEMENT main (DATA_RECORD*)>
  <!ELEMENT DATA_RECORD (ID,IDPERSONA,FECHA,MOTIVO,AUTO)+>
  <!ELEMENT ID (#PCDATA)>
  <!ELEMENT IDPERSONA (#PCDATA)>
  <!ELEMENT FECHA (#PCDATA)>
  <!ELEMENT MOTIVO (#PCDATA)>
  <!ELEMENT AUTO (#PCDATA)>
]>
<main>
  <DATA_RECORD>
    <ID>121</ID>
    <IDPERSONA>1602</IDPERSONA>
    <FECHA>2017/08/01 00:00:00</FECHA>
    <MOTIVO>VACACIONES</MOTIVO>
    <AUTO>N</AUTO>
  </DATA_RECORD>
</main>
