<?xml version="1.0" ?>
<!DOCTYPE main [
  <!ELEMENT main (DATA_RECORD*)>
  <!ELEMENT DATA_RECORD (PC_LIBR_ISBN,PC_PALABRA)+>
  <!ELEMENT PC_LIBR_ISBN (#PCDATA)>
  <!ELEMENT PC_PALABRA (#PCDATA)>
]>
<main>
  <DATA_RECORD>
    <PC_LIBR_ISBN> 9788415690832</PC_LIBR_ISBN>
    <PC_PALABRA>aguas</PC_PALABRA>
  </DATA_RECORD>
  <DATA_RECORD>
    <PC_LIBR_ISBN> 9788415690832</PC_LIBR_ISBN>
    <PC_PALABRA>ambiental</PC_PALABRA>
  </DATA_RECORD>
  <DATA_RECORD>
    <PC_LIBR_ISBN> 9788415690832</PC_LIBR_ISBN>
    <PC_PALABRA>argentina</PC_PALABRA>
  </DATA_RECORD>
  <DATA_RECORD>
    <PC_LIBR_ISBN> 9788415690832</PC_LIBR_ISBN>
    <PC_PALABRA>competencias</PC_PALABRA>
  </DATA_RECORD>
  <DATA_RECORD>
    <PC_LIBR_ISBN>551-2017</PC_LIBR_ISBN>
    <PC_PALABRA>Antig&#252;edad</PC_PALABRA>
  </DATA_RECORD>
  <DATA_RECORD>
    <PC_LIBR_ISBN>551-2017</PC_LIBR_ISBN>
    <PC_PALABRA>Congreso</PC_PALABRA>
  </DATA_RECORD>
  <DATA_RECORD>
    <PC_LIBR_ISBN>551-2017</PC_LIBR_ISBN>
    <PC_PALABRA>J&#243;venes Investigadores</PC_PALABRA>
  </DATA_RECORD>
  <DATA_RECORD>
    <PC_LIBR_ISBN>MU-686-2016</PC_LIBR_ISBN>
    <PC_PALABRA>Arte </PC_PALABRA>
  </DATA_RECORD>
  <DATA_RECORD>
    <PC_LIBR_ISBN>MU-686-2016</PC_LIBR_ISBN>
    <PC_PALABRA>cer&#225;mica</PC_PALABRA>
  </DATA_RECORD>
  <DATA_RECORD>
    <PC_LIBR_ISBN>MU-686-2016</PC_LIBR_ISBN>
    <PC_PALABRA>feminista</PC_PALABRA>
  </DATA_RECORD>
  <DATA_RECORD>
    <PC_LIBR_ISBN>978-84-00-09772-1</PC_LIBR_ISBN>
    <PC_PALABRA>Curia</PC_PALABRA>
  </DATA_RECORD>
  <DATA_RECORD>
    <PC_LIBR_ISBN>978-84-00-09772-1</PC_LIBR_ISBN>
    <PC_PALABRA>Hispania</PC_PALABRA>
  </DATA_RECORD>
  <DATA_RECORD>
    <PC_LIBR_ISBN>978-84-00-09772-1</PC_LIBR_ISBN>
    <PC_PALABRA>ordo decurionum</PC_PALABRA>
  </DATA_RECORD>
  <DATA_RECORD>
    <PC_LIBR_ISBN>978-84-09-06300-0</PC_LIBR_ISBN>
    <PC_PALABRA>Arte textil</PC_PALABRA>
  </DATA_RECORD>
  <DATA_RECORD>
    <PC_LIBR_ISBN>978-84-09-06300-0</PC_LIBR_ISBN>
    <PC_PALABRA>mediaci&#243;n art&#237;stica</PC_PALABRA>
  </DATA_RECORD>
  <DATA_RECORD>
    <PC_LIBR_ISBN>978-84-09-06300-0</PC_LIBR_ISBN>
    <PC_PALABRA>mujer</PC_PALABRA>
  </DATA_RECORD>
  <DATA_RECORD>
    <PC_LIBR_ISBN>978-84-15690-83-2</PC_LIBR_ISBN>
    <PC_PALABRA>agua</PC_PALABRA>
  </DATA_RECORD>
  <DATA_RECORD>
    <PC_LIBR_ISBN>978-84-15690-83-2</PC_LIBR_ISBN>
    <PC_PALABRA>argentina</PC_PALABRA>
  </DATA_RECORD>
  <DATA_RECORD>
    <PC_LIBR_ISBN>978-84-15690-83-2</PC_LIBR_ISBN>
    <PC_PALABRA>federalismo</PC_PALABRA>
  </DATA_RECORD>
  <DATA_RECORD>
    <PC_LIBR_ISBN>978-84-15690-83-2</PC_LIBR_ISBN>
    <PC_PALABRA>medio ambiente</PC_PALABRA>
  </DATA_RECORD>
  <DATA_RECORD>
    <PC_LIBR_ISBN>978-84-16038-32-9</PC_LIBR_ISBN>
    <PC_PALABRA>Grupo de empresas</PC_PALABRA>
  </DATA_RECORD>
  <DATA_RECORD>
    <PC_LIBR_ISBN>978-84-16038-32-9</PC_LIBR_ISBN>
    <PC_PALABRA>Relaci&#243;n individual de trabajo</PC_PALABRA>
  </DATA_RECORD>
  <DATA_RECORD>
    <PC_LIBR_ISBN>978-84-16038-73-2</PC_LIBR_ISBN>
    <PC_PALABRA>Crisis econ&#243;mica</PC_PALABRA>
  </DATA_RECORD>
  <DATA_RECORD>
    <PC_LIBR_ISBN>978-84-16038-73-2</PC_LIBR_ISBN>
    <PC_PALABRA>protecci&#243;n social</PC_PALABRA>
  </DATA_RECORD>
  <DATA_RECORD>
    <PC_LIBR_ISBN>978-84-16038-73-2</PC_LIBR_ISBN>
    <PC_PALABRA>reforma laboral</PC_PALABRA>
  </DATA_RECORD>
  <DATA_RECORD>
    <PC_LIBR_ISBN>978-84-16165-02-5</PC_LIBR_ISBN>
    <PC_PALABRA>Bergson</PC_PALABRA>
  </DATA_RECORD>
  <DATA_RECORD>
    <PC_LIBR_ISBN>978-84-16165-02-5</PC_LIBR_ISBN>
    <PC_PALABRA>Memoria</PC_PALABRA>
  </DATA_RECORD>
  <DATA_RECORD>
    <PC_LIBR_ISBN>978-84-16165-02-5</PC_LIBR_ISBN>
    <PC_PALABRA>Tiempo </PC_PALABRA>
  </DATA_RECORD>
  <DATA_RECORD>
    <PC_LIBR_ISBN>978-84-16551-02-6</PC_LIBR_ISBN>
    <PC_PALABRA>FAMILIA</PC_PALABRA>
  </DATA_RECORD>
  <DATA_RECORD>
    <PC_LIBR_ISBN>978-84-16551-02-6</PC_LIBR_ISBN>
    <PC_PALABRA>PODER CENTRAL</PC_PALABRA>
  </DATA_RECORD>
  <DATA_RECORD>
    <PC_LIBR_ISBN>978-84-16551-02-6</PC_LIBR_ISBN>
    <PC_PALABRA>PODER LOCAL</PC_PALABRA>
  </DATA_RECORD>
  <DATA_RECORD>
    <PC_LIBR_ISBN>978-84-16608-55-3</PC_LIBR_ISBN>
    <PC_PALABRA>Constituci&#243;n</PC_PALABRA>
  </DATA_RECORD>
  <DATA_RECORD>
    <PC_LIBR_ISBN>978-84-16608-55-3</PC_LIBR_ISBN>
    <PC_PALABRA>Espa&#241;a</PC_PALABRA>
  </DATA_RECORD>
  <DATA_RECORD>
    <PC_LIBR_ISBN>978-84-16608-55-3</PC_LIBR_ISBN>
    <PC_PALABRA>Italia</PC_PALABRA>
  </DATA_RECORD>
  <DATA_RECORD>
    <PC_LIBR_ISBN>978-84-16608-55-3</PC_LIBR_ISBN>
    <PC_PALABRA>Seguridad Social</PC_PALABRA>
  </DATA_RECORD>
  <DATA_RECORD>
    <PC_LIBR_ISBN>978-84-16724-32-1</PC_LIBR_ISBN>
    <PC_PALABRA>CULTURA</PC_PALABRA>
  </DATA_RECORD>
  <DATA_RECORD>
    <PC_LIBR_ISBN>978-84-16724-32-1</PC_LIBR_ISBN>
    <PC_PALABRA>HUERTA DEL BAJO SEGURA</PC_PALABRA>
  </DATA_RECORD>
  <DATA_RECORD>
    <PC_LIBR_ISBN>978-84-16724-32-1</PC_LIBR_ISBN>
    <PC_PALABRA>IDENTIDAD</PC_PALABRA>
  </DATA_RECORD>
  <DATA_RECORD>
    <PC_LIBR_ISBN>978-84-16724-32-1</PC_LIBR_ISBN>
    <PC_PALABRA>PAISAJE</PC_PALABRA>
  </DATA_RECORD>
  <DATA_RECORD>
    <PC_LIBR_ISBN>978-84-17157-24-1</PC_LIBR_ISBN>
    <PC_PALABRA>Cant&#243;n</PC_PALABRA>
  </DATA_RECORD>
  <DATA_RECORD>
    <PC_LIBR_ISBN>978-84-17157-24-1</PC_LIBR_ISBN>
    <PC_PALABRA>Cartagena</PC_PALABRA>
  </DATA_RECORD>
  <DATA_RECORD>
    <PC_LIBR_ISBN>978-84-17157-24-1</PC_LIBR_ISBN>
    <PC_PALABRA>Imagenes</PC_PALABRA>
  </DATA_RECORD>
  <DATA_RECORD>
    <PC_LIBR_ISBN>978-84-17157-24-1</PC_LIBR_ISBN>
    <PC_PALABRA>guerra</PC_PALABRA>
  </DATA_RECORD>
  <DATA_RECORD>
    <PC_LIBR_ISBN>978-84-313-3257-0</PC_LIBR_ISBN>
    <PC_PALABRA>Polo</PC_PALABRA>
  </DATA_RECORD>
  <DATA_RECORD>
    <PC_LIBR_ISBN>978-84-313-3257-0</PC_LIBR_ISBN>
    <PC_PALABRA>obras</PC_PALABRA>
  </DATA_RECORD>
  <DATA_RECORD>
    <PC_LIBR_ISBN>978-84-376-3640-5</PC_LIBR_ISBN>
    <PC_PALABRA>HISTORIA DE LA FAMILIA</PC_PALABRA>
  </DATA_RECORD>
  <DATA_RECORD>
    <PC_LIBR_ISBN>978-84-376-3640-5</PC_LIBR_ISBN>
    <PC_PALABRA>HISTORIA SOCIAL</PC_PALABRA>
  </DATA_RECORD>
  <DATA_RECORD>
    <PC_LIBR_ISBN>978-84-376-3640-5</PC_LIBR_ISBN>
    <PC_PALABRA>Poder pol&#237;tico</PC_PALABRA>
  </DATA_RECORD>
  <DATA_RECORD>
    <PC_LIBR_ISBN>978-84-376-3640-5</PC_LIBR_ISBN>
    <PC_PALABRA>Reformismo</PC_PALABRA>
  </DATA_RECORD>
  <DATA_RECORD>
    <PC_LIBR_ISBN>978-84-611-7696-0</PC_LIBR_ISBN>
    <PC_PALABRA>Asociaciones</PC_PALABRA>
  </DATA_RECORD>
  <DATA_RECORD>
    <PC_LIBR_ISBN>978-84-611-7696-0</PC_LIBR_ISBN>
    <PC_PALABRA>Consumidores</PC_PALABRA>
  </DATA_RECORD>
  <DATA_RECORD>
    <PC_LIBR_ISBN>978-84-611-7696-0</PC_LIBR_ISBN>
    <PC_PALABRA>Consumo</PC_PALABRA>
  </DATA_RECORD>
  <DATA_RECORD>
    <PC_LIBR_ISBN>978-84-697-8356-6</PC_LIBR_ISBN>
    <PC_PALABRA>M&#233;xico</PC_PALABRA>
  </DATA_RECORD>
  <DATA_RECORD>
    <PC_LIBR_ISBN>978-84-697-8356-6</PC_LIBR_ISBN>
    <PC_PALABRA>Suelos agropecuarios</PC_PALABRA>
  </DATA_RECORD>
  <DATA_RECORD>
    <PC_LIBR_ISBN>978-84-697-8356-6</PC_LIBR_ISBN>
    <PC_PALABRA>Tamaulipas</PC_PALABRA>
  </DATA_RECORD>
  <DATA_RECORD>
    <PC_LIBR_ISBN>978-84-697-8356-6</PC_LIBR_ISBN>
    <PC_PALABRA>protecci&#243;n y conservaci&#243;n</PC_PALABRA>
  </DATA_RECORD>
  <DATA_RECORD>
    <PC_LIBR_ISBN>978-84-7564-546-9</PC_LIBR_ISBN>
    <PC_PALABRA>Aceite</PC_PALABRA>
  </DATA_RECORD>
  <DATA_RECORD>
    <PC_LIBR_ISBN>978-84-7564-546-9</PC_LIBR_ISBN>
    <PC_PALABRA>Hispania</PC_PALABRA>
  </DATA_RECORD>
  <DATA_RECORD>
    <PC_LIBR_ISBN>978-84-7564-546-9</PC_LIBR_ISBN>
    <PC_PALABRA>Vino</PC_PALABRA>
  </DATA_RECORD>
  <DATA_RECORD>
    <PC_LIBR_ISBN>978-84-7564-546-9</PC_LIBR_ISBN>
    <PC_PALABRA>producci&#65533;</PC_PALABRA>
  </DATA_RECORD>
  <DATA_RECORD>
    <PC_LIBR_ISBN>978-84-842584-4-5</PC_LIBR_ISBN>
    <PC_PALABRA>Medievalismo</PC_PALABRA>
  </DATA_RECORD>
  <DATA_RECORD>
    <PC_LIBR_ISBN>978-84-842584-4-5</PC_LIBR_ISBN>
    <PC_PALABRA>j&#243;venes</PC_PALABRA>
  </DATA_RECORD>
  <DATA_RECORD>
    <PC_LIBR_ISBN>978-84-842584-4-5</PC_LIBR_ISBN>
    <PC_PALABRA>medievalistas</PC_PALABRA>
  </DATA_RECORD>
  <DATA_RECORD>
    <PC_LIBR_ISBN>978-84-9098-666-0</PC_LIBR_ISBN>
    <PC_PALABRA>Banca </PC_PALABRA>
  </DATA_RECORD>
  <DATA_RECORD>
    <PC_LIBR_ISBN>978-84-9098-666-0</PC_LIBR_ISBN>
    <PC_PALABRA>Mare Nostrum</PC_PALABRA>
  </DATA_RECORD>
  <DATA_RECORD>
    <PC_LIBR_ISBN>978-84-9148-497-4</PC_LIBR_ISBN>
    <PC_PALABRA>Brexit</PC_PALABRA>
  </DATA_RECORD>
  <DATA_RECORD>
    <PC_LIBR_ISBN>978-84-9148-497-4</PC_LIBR_ISBN>
    <PC_PALABRA>Espa&#241;a</PC_PALABRA>
  </DATA_RECORD>
  <DATA_RECORD>
    <PC_LIBR_ISBN>978-84-9148-497-4</PC_LIBR_ISBN>
    <PC_PALABRA>Reino Unido</PC_PALABRA>
  </DATA_RECORD>
  <DATA_RECORD>
    <PC_LIBR_ISBN>978-84-9148-497-4</PC_LIBR_ISBN>
    <PC_PALABRA>Uni&#243;n Europea</PC_PALABRA>
  </DATA_RECORD>
  <DATA_RECORD>
    <PC_LIBR_ISBN>978-84-9152-911-8</PC_LIBR_ISBN>
    <PC_PALABRA>INVENCIONES </PC_PALABRA>
  </DATA_RECORD>
  <DATA_RECORD>
    <PC_LIBR_ISBN>978-84-9152-911-8</PC_LIBR_ISBN>
    <PC_PALABRA>UNIVERSITARIAS</PC_PALABRA>
  </DATA_RECORD>
  <DATA_RECORD>
    <PC_LIBR_ISBN>978-84-9177-726-7</PC_LIBR_ISBN>
    <PC_PALABRA>Competencias</PC_PALABRA>
  </DATA_RECORD>
  <DATA_RECORD>
    <PC_LIBR_ISBN>978-84-9177-726-7</PC_LIBR_ISBN>
    <PC_PALABRA>Discapacidad</PC_PALABRA>
  </DATA_RECORD>
  <DATA_RECORD>
    <PC_LIBR_ISBN>978-84-9177-726-7</PC_LIBR_ISBN>
    <PC_PALABRA>Emprendimiento</PC_PALABRA>
  </DATA_RECORD>
  <DATA_RECORD>
    <PC_LIBR_ISBN>978-84-9177-726-7</PC_LIBR_ISBN>
    <PC_PALABRA>T&#233;cnica de Grupo Nominal</PC_PALABRA>
  </DATA_RECORD>
  <DATA_RECORD>
    <PC_LIBR_ISBN>978-84-92602-79-7</PC_LIBR_ISBN>
    <PC_PALABRA> concurrencia</PC_PALABRA>
  </DATA_RECORD>
  <DATA_RECORD>
    <PC_LIBR_ISBN>978-84-92602-79-7</PC_LIBR_ISBN>
    <PC_PALABRA>convenio colectivo</PC_PALABRA>
  </DATA_RECORD>
  <DATA_RECORD>
    <PC_LIBR_ISBN>978-84-92602-79-7</PC_LIBR_ISBN>
    <PC_PALABRA>descestralizaci&#243;n</PC_PALABRA>
  </DATA_RECORD>
  <DATA_RECORD>
    <PC_LIBR_ISBN>978-84-92602-79-7</PC_LIBR_ISBN>
    <PC_PALABRA>descuelgue</PC_PALABRA>
  </DATA_RECORD>
  <DATA_RECORD>
    <PC_LIBR_ISBN>978-84-942014-9-3</PC_LIBR_ISBN>
    <PC_PALABRA>Comunidades Aut&#243;nomas</PC_PALABRA>
  </DATA_RECORD>
  <DATA_RECORD>
    <PC_LIBR_ISBN>978-84-942014-9-3</PC_LIBR_ISBN>
    <PC_PALABRA>Leyes estatales</PC_PALABRA>
  </DATA_RECORD>
  <DATA_RECORD>
    <PC_LIBR_ISBN>978-84-942014-9-3</PC_LIBR_ISBN>
    <PC_PALABRA>descentralizaci&#243;n pol&#237;tica</PC_PALABRA>
  </DATA_RECORD>
  <DATA_RECORD>
    <PC_LIBR_ISBN>978-84-942014-9-3</PC_LIBR_ISBN>
    <PC_PALABRA>iniciativa legislativa</PC_PALABRA>
  </DATA_RECORD>
  <DATA_RECORD>
    <PC_LIBR_ISBN>978-84-9744-188-9</PC_LIBR_ISBN>
    <PC_PALABRA>Familia</PC_PALABRA>
  </DATA_RECORD>
  <DATA_RECORD>
    <PC_LIBR_ISBN>978-84-9744-188-9</PC_LIBR_ISBN>
    <PC_PALABRA>Historia Social</PC_PALABRA>
  </DATA_RECORD>
  <DATA_RECORD>
    <PC_LIBR_ISBN>978-84-9744-188-9</PC_LIBR_ISBN>
    <PC_PALABRA>Opini&#243;n p&#250;blica</PC_PALABRA>
  </DATA_RECORD>
  <DATA_RECORD>
    <PC_LIBR_ISBN>978-84-9744-188-9</PC_LIBR_ISBN>
    <PC_PALABRA>Siglo XIX</PC_PALABRA>
  </DATA_RECORD>
  <DATA_RECORD>
    <PC_LIBR_ISBN>978-84-9921-848-9</PC_LIBR_ISBN>
    <PC_PALABRA>Innovaci&#243;n educativa</PC_PALABRA>
  </DATA_RECORD>
  <DATA_RECORD>
    <PC_LIBR_ISBN>978-84-9921-848-9</PC_LIBR_ISBN>
    <PC_PALABRA>Investigaci&#243;n </PC_PALABRA>
  </DATA_RECORD>
  <DATA_RECORD>
    <PC_LIBR_ISBN>978-84-9921-848-9</PC_LIBR_ISBN>
    <PC_PALABRA>Tecnolog&#237;a</PC_PALABRA>
  </DATA_RECORD>
  <DATA_RECORD>
    <PC_LIBR_ISBN>978-84-9921-848-9</PC_LIBR_ISBN>
    <PC_PALABRA>ense&#241;anza-aprendizaje</PC_PALABRA>
  </DATA_RECORD>
  <DATA_RECORD>
    <PC_LIBR_ISBN>978-84-9985-005-4</PC_LIBR_ISBN>
    <PC_PALABRA>Asociaciones</PC_PALABRA>
  </DATA_RECORD>
  <DATA_RECORD>
    <PC_LIBR_ISBN>978-84-9985-005-4</PC_LIBR_ISBN>
    <PC_PALABRA>Consumidores</PC_PALABRA>
  </DATA_RECORD>
  <DATA_RECORD>
    <PC_LIBR_ISBN>978-84-9985-005-4</PC_LIBR_ISBN>
    <PC_PALABRA>Consumo</PC_PALABRA>
  </DATA_RECORD>
  <DATA_RECORD>
    <PC_LIBR_ISBN>9788415690832</PC_LIBR_ISBN>
    <PC_PALABRA>aguas</PC_PALABRA>
  </DATA_RECORD>
  <DATA_RECORD>
    <PC_LIBR_ISBN>9788416608546</PC_LIBR_ISBN>
    <PC_PALABRA>autonomo</PC_PALABRA>
  </DATA_RECORD>
  <DATA_RECORD>
    <PC_LIBR_ISBN>9788416608546</PC_LIBR_ISBN>
    <PC_PALABRA>trabajo </PC_PALABRA>
  </DATA_RECORD>
  <DATA_RECORD>
    <PC_LIBR_ISBN>9788417146078</PC_LIBR_ISBN>
    <PC_PALABRA>Francisco F&#233;lix Montiel</PC_PALABRA>
  </DATA_RECORD>
  <DATA_RECORD>
    <PC_LIBR_ISBN>9788417146078</PC_LIBR_ISBN>
    <PC_PALABRA>Guerra civil espa&#241;ola</PC_PALABRA>
  </DATA_RECORD>
  <DATA_RECORD>
    <PC_LIBR_ISBN>9788417146078</PC_LIBR_ISBN>
    <PC_PALABRA>Juristas del 27</PC_PALABRA>
  </DATA_RECORD>
  <DATA_RECORD>
    <PC_LIBR_ISBN>9788417157401</PC_LIBR_ISBN>
    <PC_PALABRA>diccionario</PC_PALABRA>
  </DATA_RECORD>
  <DATA_RECORD>
    <PC_LIBR_ISBN>9788417157401</PC_LIBR_ISBN>
    <PC_PALABRA>marroqu&#237;</PC_PALABRA>
  </DATA_RECORD>
  <DATA_RECORD>
    <PC_LIBR_ISBN>9788494679261</PC_LIBR_ISBN>
    <PC_PALABRA>Econom&#237;a</PC_PALABRA>
  </DATA_RECORD>
  <DATA_RECORD>
    <PC_LIBR_ISBN>9788494679261</PC_LIBR_ISBN>
    <PC_PALABRA>La Manga</PC_PALABRA>
  </DATA_RECORD>
  <DATA_RECORD>
    <PC_LIBR_ISBN>9788494679261</PC_LIBR_ISBN>
    <PC_PALABRA>Sociedad</PC_PALABRA>
  </DATA_RECORD>
  <DATA_RECORD>
    <PC_LIBR_ISBN>9788494679261</PC_LIBR_ISBN>
    <PC_PALABRA>Urbanismo</PC_PALABRA>
  </DATA_RECORD>
  <DATA_RECORD>
    <PC_LIBR_ISBN>9788494782275</PC_LIBR_ISBN>
    <PC_PALABRA>Espa&#241;a</PC_PALABRA>
  </DATA_RECORD>
  <DATA_RECORD>
    <PC_LIBR_ISBN>9788494782275</PC_LIBR_ISBN>
    <PC_PALABRA>Historia social</PC_PALABRA>
  </DATA_RECORD>
  <DATA_RECORD>
    <PC_LIBR_ISBN>9788494782275</PC_LIBR_ISBN>
    <PC_PALABRA>Movimiento obrero</PC_PALABRA>
  </DATA_RECORD>
  <DATA_RECORD>
    <PC_LIBR_ISBN>9788494782275</PC_LIBR_ISBN>
    <PC_PALABRA>PSOE</PC_PALABRA>
  </DATA_RECORD>
  <DATA_RECORD>
    <PC_LIBR_ISBN>9788494812392</PC_LIBR_ISBN>
    <PC_PALABRA>aut&#243;nomo</PC_PALABRA>
  </DATA_RECORD>
  <DATA_RECORD>
    <PC_LIBR_ISBN>9788494812392</PC_LIBR_ISBN>
    <PC_PALABRA>explotaci&#243;n</PC_PALABRA>
  </DATA_RECORD>
  <DATA_RECORD>
    <PC_LIBR_ISBN>9788494812392</PC_LIBR_ISBN>
    <PC_PALABRA>menores</PC_PALABRA>
  </DATA_RECORD>
  <DATA_RECORD>
    <PC_LIBR_ISBN>M-1895-2016</PC_LIBR_ISBN>
    <PC_PALABRA>discurso del odio</PC_PALABRA>
  </DATA_RECORD>
  <DATA_RECORD>
    <PC_LIBR_ISBN>M-1895-2016</PC_LIBR_ISBN>
    <PC_PALABRA>libertad de expresi&#243;n</PC_PALABRA>
  </DATA_RECORD>
  <DATA_RECORD>
    <PC_LIBR_ISBN>M-1895-2016</PC_LIBR_ISBN>
    <PC_PALABRA>negacionismo</PC_PALABRA>
  </DATA_RECORD>
  <DATA_RECORD>
    <PC_LIBR_ISBN>MU 1139-2016</PC_LIBR_ISBN>
    <PC_PALABRA>Cl&#65533;rigos</PC_PALABRA>
  </DATA_RECORD>
  <DATA_RECORD>
    <PC_LIBR_ISBN>MU 1139-2016</PC_LIBR_ISBN>
    <PC_PALABRA>Religiosos</PC_PALABRA>
  </DATA_RECORD>
  <DATA_RECORD>
    <PC_LIBR_ISBN>MU 1139-2016</PC_LIBR_ISBN>
    <PC_PALABRA>Secularizados</PC_PALABRA>
  </DATA_RECORD>
  <DATA_RECORD>
    <PC_LIBR_ISBN>MU 1139-2016</PC_LIBR_ISBN>
    <PC_PALABRA>Seguridad Social</PC_PALABRA>
  </DATA_RECORD>
  <DATA_RECORD>
    <PC_LIBR_ISBN>MU-323-2016</PC_LIBR_ISBN>
    <PC_PALABRA>ARTE</PC_PALABRA>
  </DATA_RECORD>
  <DATA_RECORD>
    <PC_LIBR_ISBN>MU-323-2016</PC_LIBR_ISBN>
    <PC_PALABRA>INMIGRACI&#211;N</PC_PALABRA>
  </DATA_RECORD>
  <DATA_RECORD>
    <PC_LIBR_ISBN>MU-36-2016</PC_LIBR_ISBN>
    <PC_PALABRA>Adela Cortina</PC_PALABRA>
  </DATA_RECORD>
  <DATA_RECORD>
    <PC_LIBR_ISBN>MU-36-2016</PC_LIBR_ISBN>
    <PC_PALABRA>Filosof&#237;a pol&#237;tica</PC_PALABRA>
  </DATA_RECORD>
  <DATA_RECORD>
    <PC_LIBR_ISBN>MU-36-2016</PC_LIBR_ISBN>
    <PC_PALABRA>&#201;tica</PC_PALABRA>
  </DATA_RECORD>
  <DATA_RECORD>
    <PC_LIBR_ISBN>MU-554-2017</PC_LIBR_ISBN>
    <PC_PALABRA>EN CAMBIO</PC_PALABRA>
  </DATA_RECORD>
  <DATA_RECORD>
    <PC_LIBR_ISBN>MU-554-2017</PC_LIBR_ISBN>
    <PC_PALABRA>LA UNIVERSIDAD</PC_PALABRA>
  </DATA_RECORD>
  <DATA_RECORD>
    <PC_LIBR_ISBN>MU-554-2017</PC_LIBR_ISBN>
    <PC_PALABRA>MIRADAS </PC_PALABRA>
  </DATA_RECORD>
  <DATA_RECORD>
    <PC_LIBR_ISBN>MU-554-2017</PC_LIBR_ISBN>
    <PC_PALABRA>M&#218;LTIPLES</PC_PALABRA>
  </DATA_RECORD>
</main>
