<?xml version="1.0" ?>
<!DOCTYPE main [
  <!ELEMENT main (DATA_RECORD*)>
  <!ELEMENT DATA_RECORD (IDDOCUMENTO?,IDDOCUMENTOSOLICITUD?,IDPERSONASOLICITANTE?,PUNTUACION?)+>
  <!ELEMENT IDDOCUMENTO (#PCDATA)>
  <!ELEMENT IDDOCUMENTOSOLICITUD (#PCDATA)>
  <!ELEMENT IDPERSONASOLICITANTE (#PCDATA)>
  <!ELEMENT PUNTUACION (#PCDATA)>
]>
<main>
  <DATA_RECORD>
    <IDDOCUMENTO>RRHC-B-2016-10144</IDDOCUMENTO>
    <IDDOCUMENTOSOLICITUD>SRH-B-2015-10144</IDDOCUMENTOSOLICITUD>
    <IDPERSONASOLICITANTE></IDPERSONASOLICITANTE>
    <PUNTUACION></PUNTUACION>
  </DATA_RECORD>
</main>
