<?xml version="1.0" ?>
<!DOCTYPE main [
  <!ELEMENT main (DATA_RECORD*)>
  <!ELEMENT DATA_RECORD (IDDEPENDENCIA,NUMERO,IDPROYECTO)+>
  <!ELEMENT IDDEPENDENCIA (#PCDATA)>
  <!ELEMENT NUMERO (#PCDATA)>
  <!ELEMENT IDPROYECTO (#PCDATA)>
]>
<main>
  <DATA_RECORD>
    <IDDEPENDENCIA>COP-2007-5078</IDDEPENDENCIA>
    <NUMERO>1</NUMERO>
    <IDPROYECTO>10849</IDPROYECTO>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDEPENDENCIA>COP-2007-5078</IDDEPENDENCIA>
    <NUMERO>2</NUMERO>
    <IDPROYECTO>10848</IDPROYECTO>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDEPENDENCIA>COP-2007-5238</IDDEPENDENCIA>
    <NUMERO>1</NUMERO>
    <IDPROYECTO>11117</IDPROYECTO>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDEPENDENCIA>COP-2007-5238</IDDEPENDENCIA>
    <NUMERO>2</NUMERO>
    <IDPROYECTO>11116</IDPROYECTO>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDEPENDENCIA>COP-2008-5300</IDDEPENDENCIA>
    <NUMERO>1</NUMERO>
    <IDPROYECTO>11384</IDPROYECTO>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDEPENDENCIA>COP-2008-5300</IDDEPENDENCIA>
    <NUMERO>2</NUMERO>
    <IDPROYECTO>11383</IDPROYECTO>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDEPENDENCIA>COP-2010-6070</IDDEPENDENCIA>
    <NUMERO>1</NUMERO>
    <IDPROYECTO>13882</IDPROYECTO>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDEPENDENCIA>COP-2010-6070</IDDEPENDENCIA>
    <NUMERO>2</NUMERO>
    <IDPROYECTO>14024</IDPROYECTO>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDEPENDENCIA>COP-2012-6636</IDDEPENDENCIA>
    <NUMERO>1</NUMERO>
    <IDPROYECTO>14607</IDPROYECTO>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDEPENDENCIA>COP-2012-6636</IDDEPENDENCIA>
    <NUMERO>2</NUMERO>
    <IDPROYECTO>14608</IDPROYECTO>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDEPENDENCIA>COP-2012-7045</IDDEPENDENCIA>
    <NUMERO>1</NUMERO>
    <IDPROYECTO>15605</IDPROYECTO>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDEPENDENCIA>COP-2012-7045</IDDEPENDENCIA>
    <NUMERO>2</NUMERO>
    <IDPROYECTO>15606</IDPROYECTO>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDEPENDENCIA>COP-2013-7453</IDDEPENDENCIA>
    <NUMERO>1</NUMERO>
    <IDPROYECTO>16886</IDPROYECTO>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDEPENDENCIA>COP-2013-7453</IDDEPENDENCIA>
    <NUMERO>2</NUMERO>
    <IDPROYECTO>16887</IDPROYECTO>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDEPENDENCIA>COP-2013-7476</IDDEPENDENCIA>
    <NUMERO>1</NUMERO>
    <IDPROYECTO>16832</IDPROYECTO>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDEPENDENCIA>COP-2013-7476</IDDEPENDENCIA>
    <NUMERO>2</NUMERO>
    <IDPROYECTO>19332</IDPROYECTO>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDEPENDENCIA>COP-2014-7650</IDDEPENDENCIA>
    <NUMERO>1</NUMERO>
    <IDPROYECTO>17537</IDPROYECTO>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDEPENDENCIA>COP-2014-7650</IDDEPENDENCIA>
    <NUMERO>2</NUMERO>
    <IDPROYECTO>17538</IDPROYECTO>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDEPENDENCIA>COP-2014-7879</IDDEPENDENCIA>
    <NUMERO>1</NUMERO>
    <IDPROYECTO>17802</IDPROYECTO>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDEPENDENCIA>COP-2014-7879</IDDEPENDENCIA>
    <NUMERO>2</NUMERO>
    <IDPROYECTO>17803</IDPROYECTO>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDEPENDENCIA>COP-2015-8293</IDDEPENDENCIA>
    <NUMERO>1</NUMERO>
    <IDPROYECTO>19852</IDPROYECTO>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDEPENDENCIA>COP-2015-8293</IDDEPENDENCIA>
    <NUMERO>2</NUMERO>
    <IDPROYECTO>19859</IDPROYECTO>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDEPENDENCIA>COP-2016-8788</IDDEPENDENCIA>
    <NUMERO>1</NUMERO>
    <IDPROYECTO>25815</IDPROYECTO>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDDEPENDENCIA>COP-2016-8788</IDDEPENDENCIA>
    <NUMERO>2</NUMERO>
    <IDPROYECTO>25816</IDPROYECTO>
  </DATA_RECORD>
</main>
